In [121]:
import numpy as np

In [122]:
class Dataset:
  
  def __init__(self,my_path):
    self.data = []
    self.my_path = my_path
    self.open_file()

  def open_file(self):
    #read the data
    f = open(self.my_path, 'r')
    for line in f:
      self.data.append(line.split(','))

  def mapping(self,col): # This method is mapping all unique values to integers and returns an encoded version of the given list
    # Create a dictionary with all the unique values found in the list and give them a unique code number
    dictionary = {}
    counter = 0
    for x in col:
      if x not in dictionary:
        dictionary[x] = counter
        counter += 1
    #print(dictionary)
    # Replace all values in the column with the encoded version and return the result
    for i in range(0,len(col)):
      col[i] = dictionary[col[i]]
    return col

  def col_to_list(self,col_no): #This method, given the column index, returns it as a list 
    temp_col = []
    for i in range(0,len(d.data)):
      temp_col.append(d.data[i][col_no])
    return temp_col

  def one_hot_encoding(self,col): # This method returns the one-hot-encoded version of a list as a list of lists 
    dictionary = {}
    counter = 0
    for x in col:
      if x not in dictionary:
        dictionary[x] = counter
        counter += 1
    #print(dictionary)
    z = np.zeros((len(col),len(dictionary)), dtype='int') 
    for x in range (0,len(col)): #iterate the columns
      z[x][dictionary[col[x]]] = 1
    return z

  def binary_encoding(self,col): # reuturns the binary encoded form of list in numpy array where each bit is in differet column.
    col = self.mapping(col)
    max_digits = len(self.decimalToBinary(max(col)))
    z = np.zeros((len(col),max_digits), dtype='int')
    for i in range(0,len(col)):
      num = self.decimalToBinary(col[i])
      digits = len(num)
      for j in range(0,max_digits):
        if (j < digits):
          z[i][j] = num[j]
        else:
          z[i][j] = -1 #-1 is not a part of the decimal and represents the end of the number
    return z

  def decimalToBinary(self, num):       
      return bin(num)[2:]

  def mapping_all(self): #This method is encoding all categorical columns
    for x in range (0,len(self.data[0])): #iterate the columns
      col = []
      if (not self.data[0][x].isdigit()): # check if the first element of the column is digit or string
        col = self.mapping(self.col_to_list(x)) # convert the strings column to an encoded version
      for i in range (0,len(col)): # replace the old with the new values
        self.data[i][x] = str(col[i])
  
  def create_numpy_array(self):
    for i in range (0,len(self.data[0])): # convert all values to int
      for j in range (0,len(self.data)):
        self.data[j][i] = int(self.data[j][i]) 
    self.ndata = np.array(self.data, dtype='int') # store numpy array into the instance value ndata
    return self.ndata
    
  def calc_mean(self):
      col_mean = []
      for j in range (len(self.ndata[0])):
        temp = 0
        for i in range (len(self.ndata)):
          temp += self.ndata[i][j]
        col_mean.append(temp/len(self.ndata))
      return col_mean

  def calc_var(self):
    col_var = []
    col_mean = self.calc_mean()
    for j in range (len(self.ndata[0])):
      temp = 0
      for i in range (len(self.ndata)):
        temp += (col_mean[j] - self.ndata[i][j]) ** 2
      col_var.append(temp/len(self.ndata))
    return col_var

  def calc_median(self):
    col_median = []
    for j in range (len(self.ndata[0])):
      temp_list = []
      for i in range (len(self.ndata)):
        temp_list.append(self.ndata[i][j])
      temp_list.sort()
      col_median.append(temp_list[len(temp_list)//2])
    return col_median

  def normalize(self):
    min_col = np.amin(self.ndata, axis=0)
    max_col = np.amax(self.ndata, axis=0)
    self.ndata = self.ndata.astype(float)
    for i in range(0,len(self.ndata[0])):
      for j in range(0,len(self.ndata)):
        self.ndata[j][i] = (self.ndata[j][i] - min_col[i]) / (max_col[i] - min_col[i])   

  def standarize(self):
    mean_col = self.calc_mean()
    std_col = np.std(self.ndata,axis=0)
    self.ndata = self.ndata.astype(float)
    for i in range(0,len(self.ndata[0])):
      for j in range(0,len(self.ndata)):
        self.ndata[j][i] = (self.ndata[j][i] - mean_col[i]) / std_col[i]   


#Task 1 results

In [123]:
d = Dataset('/content/data.csv')
a = d.mapping(d.col_to_list(1))
print(a)

[0, 1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 4, 0, 2, 1, 1, 0, 0, 0, 0, 5, 0, 0, 0, 0, 1, 0, 0, 3, 2, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 1, 0, 4, 0, 6, 0, 0, 4, 6, 2, 0, 0, 0, 3, 0, 0, 0, 4, 2, 3, 0, 2, 0, 0, 5, 0, 0, 0, 0, 1, 5, 0, 1, 0, 4, 0, 0, 0, 0, 4, 4, 0, 2, 2, 0, 5, 0, 0]


In [124]:
b = d.one_hot_encoding(d.col_to_list(1))
print(b[0:5])

[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0]]


In [125]:
d = Dataset('/content/data.csv')
a = d.binary_encoding(d.col_to_list(1))
print(a[:5])

[[ 0 -1 -1]
 [ 1 -1 -1]
 [ 1  0 -1]
 [ 1  1 -1]
 [ 0 -1 -1]]


#Task 2 results

In [126]:
d = Dataset('/content/data.csv')
d.mapping_all()
c = d.create_numpy_array()
print('The array type is: ', type(c))
print (c[0:3])
mean = d.calc_mean()
median = d.calc_median()
variance = d.calc_var()
for i in range(0,len(mean)):
  print('The mean of column ', i , ' is : ' , mean[i] , ', the variance is : ' , variance[i] , ' and the median is : ' , median[i])

The array type is:  <class 'numpy.ndarray'>
[[    28      0  37821      0     11      0      0      0      0      0
       0      0     55      0]
 [    33      1 119829      1      9      1      1      1      0      0
       0      0     60      1]
 [    70      2 177199      1      9      1      2      2      0      1
       0      0      3      1]]
The mean of column  0  is :  41.04 , the variance is :  239.97840000000005  and the median is :  38
The mean of column  1  is :  1.01 , the variance is :  2.709900000000003  and the median is :  0
The mean of column  2  is :  172838.44 , the variance is :  8693090829.1664  and the median is :  169973
The mean of column  3  is :  3.22 , the variance is :  7.811599999999999  and the median is :  3
The mean of column  4  is :  10.29 , the variance is :  6.245900000000001  and the median is :  10
The mean of column  5  is :  1.21 , the variance is :  1.5258999999999998  and the median is :  1
The mean of column  6  is :  4.19 , the variance i

#Task 3 answers

1) Since strings can be used to represent both characters and numbers, why
isn’t it effective to store the data as an array of strings?
*   With strings its not possible to perform mathematical calculations
*   Its easy for machine learning algorithms to handle numbers
*   Strings require more memory than ints and floats so there is a possibility of performance loss




2) How many columns are needed encode a column with each N unique values,
with each of the 3 encoding strategies?
*   Mapping: 1 column
*   One-hot-encoding: N columns
*   Binary: As many columns as the number of bits needed to represent N in binary format 



#Task 4 results

In [127]:
d = Dataset('/content/data.csv')
d.mapping_all()
d.create_numpy_array()
d.normalize()
print(d.ndata)

[[0.13888889 0.         0.03319837 ... 0.         0.63855422 0.        ]
 [0.20833333 0.16666667 0.22704184 ... 0.         0.69879518 0.1       ]
 [0.72222222 0.33333333 0.36264812 ... 0.         0.01204819 0.1       ]
 ...
 [0.54166667 0.83333333 0.27816897 ... 0.         0.45783133 0.1       ]
 [0.26388889 0.         0.82434295 ... 0.         0.55421687 0.1       ]
 [0.18055556 0.         0.88704519 ... 0.         0.48192771 0.1       ]]


In [128]:
d = Dataset('/content/data.csv')
d.mapping_all()
d.create_numpy_array()
d.standarize()
print(d.ndata)

[[-0.84176626 -0.61354263 -1.44811403 ... -0.16355896  1.18891581
  -0.87268157]
 [-0.51900312 -0.00607468 -0.56854665 ... -0.16355896  1.54150057
  -0.26241474]
 [ 1.86944409  0.60139327  0.04676868 ... -0.16355896 -2.4779657
  -0.26241474]
 ...
 [ 1.03025993  2.42379711 -0.33655658 ... -0.16355896  0.13116153
  -0.26241474]
 [-0.26079261 -0.61354263  2.14171524 ... -0.16355896  0.69529715
  -0.26241474]
 [-0.64810838 -0.61354263  2.42622753 ... -0.16355896  0.27219544
  -0.26241474]]
